name = "BuildConstructors"
uuid = "63b9b590-f22f-4e79-810f-ea9ba6849c26"
authors = ["Robert Hentges <robert.hentges@cern.ch>"]
version = "0.7.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NumericalDistributions = "13416b18-ec19-40e4-a123-e345ab61da74"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[extensions]
PhysicsModelsExt = ["Distributions", "JSON", "NumericalDistributions", "Polynomials", "SpecialFunctions"]

[compat]
ComponentArrays = ">=0.15"
Distributions = ">=0.25"
JSON = ">=0.21.4"
NumericalDistributions = ">=0.5.3"
OrderedCollections = "1.8.1"
Polynomials = "4, 5"
SpecialFunctions = "2"
julia = "1.9"
Test = ">=1"

[extras]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NumericalDistributions = "13416b18-ec19-40e4-a123-e345ab61da74"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = [
    "Test",
    "ComponentArrays",
    "Distributions",
    "JSON",
    "NumericalDistributions",
    "Polynomials",
    "SpecialFunctions",
]
